apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3proxy.secret | default "s3proxy-secret" }}
type: Opaque
data: 
  LOG_LEVEL: {{ .Values.log_level | default "info" }}
  {{- with .Values.jclouds }}
  JCLOUDS_ENDPOINT: {{ .endpoint | default "http://0.0.0.0:80" }}
  JCLOUDS_IDENTITY: {{ .identity | default "remote-identity" }}
  JCLOUDS_CREDENTIAL: {{ .credential | default "remote-credential" }}
  JCLOUDS_KEYSTONE_PROJECT_DOMAIN_NAME: {{ .keystone.project-domain-name | default "" }}
  JCLOUDS_KEYSTONE_SCOPE: {{ .keystone.scope | default "" }}
  JCLOUDS_KEYSTONE_VERSION: {{ .keystone.version | default "" }}
  JCLOUDS_PROVIDER: {{ .provider | default "filesystem" }}
  JCLOUDS_REGION: {{ .region | default "" }}
  JCLOUDS_REGIONS: {{ .regions | default "us-east-1" }}
  JCLOUDS_FILESYSTEM_BASEDIR: {{ .filesystem.basedir | default "/data" }}
  {{- end }}
  {{- with .Values.s3proxy }}
  S3PROXY_AUTHORIZATION: {{ .authorization | default "" }}
  S3PROXY_CREDENTIAL: {{ .credential | default "local-credential" }}
  S3PROXY_VIRTUALHOST: {{ .virtual-host | default "" }}
  S3PROXY_IDENTITY:  {{ .identity | default "local-identity" }}
  S3PROXY_KEYSTORE_PASSWORD: {{ .keystore-password | default "" }}
  S3PROXY_KEYSTORE_PATH: {{ .keystore-path | default "keystore.jks" }}
  S3PROXY_CORS_ALLOW_ALL: {{ .cors-allow-all | default "" }}
  S3PROXY_CORS_ALLOW_ORIGINS: {{ .cors-allow-origins | default "" }}
  S3PROXY_CORS_ALLOW_METHODS: {{ .cors-allow-methods | default "" }}
  S3PROXY_CORS_ALLOW_HEADERS: {{ .cors-allow-headers | default "" }}
  S3PROXY_IGNORE_UNKNOWN_HEADERS: {{ .ignore-unknown-headers | default "false" }}
  S3PROXY_ENCRYPTED_BLOBSTORE: {{ .encrypted-blobstore | default "" }}
  S3PROXY_ENCRYPTED_BLOBSTORE_PASSWORD: {{ .encrypted-blobstore-password | default "" }}
  S3PROXY_ENCRYPTED_BLOBSTORE_SALT:  {{ .encrypted-blobstore-salt | default "" }}
  {{- end }}
